server:
  port: 8080

spring:
  application:
    name: sports-api

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  output:
    ansi:
      enabled: ${OUTPUT_ANSI_ENABLED:ALWAYS}
  main:
    banner-mode: OFF

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
              - email
              - profile

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}