create table tb_match_statistics (
     id uuid not null primary key,
     match_id uuid not null,
     team_id uuid not null,
     shots_on_goal integer,
     shots_off_goal integer,
     total_shots integer,
     blocked_shots integer,
     shots_inside_box integer,
     shots_outside_box integer,
     fouls integer,
     corner_kicks integer,
     offsides integer,
     ball_possession_percentage integer,
     yellow_cards integer,
     red_cards integer,
     goalkeeper_saves integer,
     total_passes integer,
     passes_accurate integer,
     passes_accuracy_percentage integer,
     constraint uk_match_statistics_match_team unique (match_id, team_id),
     constraint fk_match_statistics_match foreign key (match_id) references tb_matches(id),
     constraint fk_match_statistics_team foreign key (team_id) references tb_teams(id)
);